### ISSUE TITLE
Doesn't look like you :)

### ISSUE THREAD

**Issue by liamcmitchell** [sapnasivakumar/sapnasivakumar.github.io#1]
https://github.com/sapnasivakumar/sapnasivakumar.github.io/blob/84c4d5b57b2a02a1edc620f96fc4c00cecc14afa/index.html#L63

**Comment by sapnasivakumar** [comment]
Oops!!! My bad :( 
Fixed the issue in the following commit,
https://github.com/sapnasivakumar/sapnasivakumar.github.io/commit/0bf87b46783ebd80d0a8f4c3672152e00e3269d1

Thank You,
Sapna
